matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
        - MATRIX_EVAL_CMAKE="CMAKE_CXX_COMPILER=g++-7 && CMAKE_CC_COMPILER=gcc-7"

language: c++

before_install:
  - brew update
  - brew outdated ninja || brew upgrade ninja
  - brew outdated mpv || brew upgrade mpv
  - brew outdated conan || brew upgrade conan
  - mkdir build
  - cd build
  - eval "${MATRIX_EVAL}"
  - eval "${MATRIX_EVAL_CMAKE}"

script:
  cmake -GXcode ..